# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/charlie/Projects/x10 gui/ui/MainWindow.ui'
#
# Created: Tue Jan 11 17:20:32 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(479, 419)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_ServerAddr = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_ServerAddr.setEnabled(False)
        self.lineEdit_ServerAddr.setObjectName("lineEdit_ServerAddr")
        self.gridLayout.addWidget(self.lineEdit_ServerAddr, 1, 0, 1, 1)
        self.pushButton_Connect = QtGui.QPushButton(self.centralWidget)
        self.pushButton_Connect.setEnabled(False)
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.gridLayout.addWidget(self.pushButton_Connect, 1, 2, 1, 1)
        self.pushButton_Exit = QtGui.QPushButton(self.centralWidget)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.gridLayout.addWidget(self.pushButton_Exit, 3, 2, 1, 1)
        self.lineEdit_ServerPort = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_ServerPort.setEnabled(False)
        self.lineEdit_ServerPort.setObjectName("lineEdit_ServerPort")
        self.gridLayout.addWidget(self.lineEdit_ServerPort, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.checkBox_RemoteServer = QtGui.QCheckBox(self.centralWidget)
        self.checkBox_RemoteServer.setObjectName("checkBox_RemoteServer")
        self.gridLayout.addWidget(self.checkBox_RemoteServer, 0, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.dial_HouseCode = QtGui.QDial(self.tab)
        self.dial_HouseCode.setGeometry(QtCore.QRect(20, 30, 91, 101))
        self.dial_HouseCode.setMinimum(1)
        self.dial_HouseCode.setMaximum(16)
        self.dial_HouseCode.setObjectName("dial_HouseCode")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_UnitCode = QtGui.QLabel(self.tab)
        self.label_UnitCode.setGeometry(QtCore.QRect(120, 190, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_UnitCode.setFont(font)
        self.label_UnitCode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_UnitCode.setObjectName("label_UnitCode")
        self.dial = QtGui.QDial(self.tab)
        self.dial.setGeometry(QtCore.QRect(20, 150, 91, 91))
        self.dial.setMinimum(1)
        self.dial.setMaximum(16)
        self.dial.setObjectName("dial")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 130, 71, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_HouseCode = QtGui.QLabel(self.tab)
        self.label_HouseCode.setGeometry(QtCore.QRect(120, 70, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_HouseCode.setFont(font)
        self.label_HouseCode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_HouseCode.setObjectName("label_HouseCode")
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 250, 178, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Off = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Off.setObjectName("pushButton_Off")
        self.horizontalLayout.addWidget(self.pushButton_Off)
        self.pushButton_On = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_On.setObjectName("pushButton_On")
        self.horizontalLayout.addWidget(self.pushButton_On)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_CmdText = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_CmdText.setGeometry(QtCore.QRect(20, 10, 341, 25))
        self.lineEdit_CmdText.setObjectName("lineEdit_CmdText")
        self.pushButton_SendManualCmd = QtGui.QPushButton(self.tab_2)
        self.pushButton_SendManualCmd.setGeometry(QtCore.QRect(370, 10, 81, 27))
        self.pushButton_SendManualCmd.setObjectName("pushButton_SendManualCmd")
        self.textEdit_CmdOutput = QtGui.QTextEdit(self.tab_2)
        self.textEdit_CmdOutput.setGeometry(QtCore.QRect(20, 40, 431, 201))
        self.textEdit_CmdOutput.setReadOnly(True)
        self.textEdit_CmdOutput.setObjectName("textEdit_CmdOutput")
        self.pushButton_Clear = QtGui.QPushButton(self.tab_2)
        self.pushButton_Clear.setGeometry(QtCore.QRect(360, 250, 86, 27))
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pushButton_Exit, QtCore.SIGNAL("released()"), MainWindow.close)
        QtCore.QObject.connect(self.pushButton_Clear, QtCore.SIGNAL("clicked()"), self.textEdit_CmdOutput.clear)
        QtCore.QObject.connect(self.lineEdit_CmdText, QtCore.SIGNAL("returnPressed()"), self.pushButton_SendManualCmd.click)
        QtCore.QObject.connect(self.dial, QtCore.SIGNAL("valueChanged(int)"), self.label_UnitCode.setNum)
        QtCore.QObject.connect(self.checkBox_RemoteServer, QtCore.SIGNAL("clicked(bool)"), self.pushButton_Connect.setEnabled)
        QtCore.QObject.connect(self.checkBox_RemoteServer, QtCore.SIGNAL("clicked(bool)"), self.lineEdit_ServerPort.setEnabled)
        QtCore.QObject.connect(self.checkBox_RemoteServer, QtCore.SIGNAL("clicked(bool)"), self.lineEdit_ServerAddr.setEnabled)
        QtCore.QObject.connect(self.checkBox_RemoteServer, QtCore.SIGNAL("clicked(bool)"), self.tabWidget.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "X10 Remote Client", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ServerAddr.setText(QtGui.QApplication.translate("MainWindow", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Connect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ServerPort.setText(QtGui.QApplication.translate("MainWindow", "29876", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Host IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Host Port", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_RemoteServer.setText(QtGui.QApplication.translate("MainWindow", "Remote Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "House Code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_UnitCode.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Unit Code", None, QtGui.QApplication.UnicodeUTF8))
        self.label_HouseCode.setText(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Off.setText(QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_On.setText(QtGui.QApplication.translate("MainWindow", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "X10 Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SendManualCmd.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Clear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Manual Commands", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

